import { z } from "zod";
import { toolHandler, jsonText } from "./util.js";

export function registerReadTools(server, dxm) {
    server.tool(
        "list_users",
        "List the users visible to the authenticated session on this DXM instance",
        {},
        toolHandler(async () => jsonText(await dxm.listUsers()))
    );
}

export function registerWriteTools(server, dxm) {
    server.tool(
        "create_user",
        "Create a new DXM user. Omit password to have the CMS auto-generate a one-time-use password.",
        {
            username: z.string().describe("The username"),
            first_name: z.string().describe("The first name"),
            last_name: z.string().describe("The last name"),
            email_address: z.string().describe("The email address"),
            password: z.string().optional().describe("Optional password; if omitted, a one-time-use password is generated by the CMS")
        },
        toolHandler(async ({username, first_name, last_name, email_address, password}) =>
            jsonText(await dxm.createUser({
                username,
                firstName: first_name,
                lastName: last_name,
                emailAddress: email_address,
                password
            }))
        )
    );
}
